apiVersion: v1
kind: Pod
metadata:
      name: web-pod
      labels: 
        tier: frontend
        name: frontend-pod
        app: laugh-generator
spec:
  containers: 
    - name: web-ui
      image: oliviabaldwin321/laugh-generator:web-ui
      ports: 
        - containerPort: 3000