apiVersion: v1
kind: Pod
metadata:
      name: server-pod
      labels: 
        tier: backend
        name: backend-pod
        app: laugh-generator
spec:
  containers: 
    - name: python-docker
      image: oliviabaldwin321/laugh-generator:python-docker
      ports: 
        - containerPort: 5000